# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ProcessingUMEP
                                 A QGIS plugin
 UMEP for processing toolbox
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-04-02
        copyright            : (C) 2020 by Fredrik Lindberg
        email                : fredrikl@gvc.gu.se
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Fredrik Lindberg"
__date__ = "2020-04-02"
__copyright__ = "(C) 2020 by Fredrik Lindberg"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import gc

import gc

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterNumber,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterRasterDestination,
)

from osgeo import gdal
from osgeo.gdalconst import *

try:
    import torch
except ImportError:
    torch = None
    ipex = None

import os
from ..functions import wallalgorithms_torch as wa_torch
from ..functions import wallalgorithms as wa

from qgis.PyQt.QtGui import QIcon
import inspect
from pathlib import Path
from ..util.misc import saverasternd
import os


class ProcessingWallHeightAscpetAlgorithm(QgsProcessingAlgorithm):

    INPUT_LIMIT = "INPUT_LIMIT"
    INPUT = "INPUT"
    USE_GPU = "USE_GPU"
    OUTPUT_HEIGHT = "OUTPUT_HEIGHT"
    OUTPUT_ASPECT = "OUTPUT_ASPECT"

    def initAlgorithm(self, config):

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr("Input building and ground DSM"),
                None,
                False,
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.INPUT_LIMIT,
                self.tr("Lower limit for wall height (m)"),
                QgsProcessingParameterNumber.Type.Double,
                QVariant(3.0),
                minValue=0.0,
            )
        )
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.USE_GPU,
                self.tr("Use GPU if available"),
                None,
                False,
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT_HEIGHT,
                self.tr("Output Wall Height Raster"),
                None,
                False,
            )
        )
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT_ASPECT,
                self.tr("Output Wall Aspect Raster"),
                optional=True,
                createByDefault=False,
            )
        )

    def processAlgorithm(self, parameters, context, feedback):

        outputFileHeight = self.parameterAsOutputLayer(
            parameters, self.OUTPUT_HEIGHT, context
        )
        outputFileAspect = self.parameterAsOutputLayer(
            parameters, self.OUTPUT_ASPECT, context
        )
        dsmin = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        # aspectcalculation = self.parameterAsBool(parameters, self.ASPECT_BOOL, context)
        walllimit = self.parameterAsDouble(
            parameters, self.INPUT_LIMIT, context
        )
        use_gpu = self.parameterAsBool(parameters, self.USE_GPU, context)

        cmd_folder = Path(
            os.path.split(inspect.getfile(inspect.currentframe()))[0]
        )
        feedback.setProgressText(str(cmd_folder))
        feedback.setProgressText(str(cmd_folder.parent))
        device = None

        if use_gpu:

            # Safely identify if we are dealing with the local mock class
            if (
                type(torch).__name__ == "MetaMock"
                or getattr(torch, "__name__", "") == "LocalMockTorch"
            ):
                raise QgsProcessingException(
                    "\n[UMEP Error] PyTorch is required to run GPU mode.\n"
                    "Please install it using: pip install torch or with osgeo4w.\n"
                    "Note:  setup for intel GPU require a more complex setup :\n"
                    "pip install torch --index-url https://download.pytorch.org/whl/xpu"
                )

            if torch.cuda.is_available():
                device = torch.device("cuda")
                if feedback is not None:

                    feedback.setProgressText(
                        "PyTorch and GPU found. Initiating GPU mode..."
                    )
            elif hasattr(torch, "xpu") and torch.xpu.is_available():
                device = torch.device("xpu")
                if feedback is not None:
                    feedback.setProgressText(
                        "PyTorch and GPU found. Initiating intel GPU mode..."
                    )
            else:
                device = torch.device("cpu")
                if feedback is not None:

                    feedback.setProgressText(
                        "Pytorch found but GPU not found. Initiating CPU mode..."
                    )

        else:
            # Fall back to standard CPU processing
            if feedback is not None:
                feedback.setProgressText("Running in CPU mode...")

        provider = dsmin.dataProvider()
        filepath_dsm = str(provider.dataSourceUri())
        gdal_dsm = gdal.Open(filepath_dsm)
        dsm = gdal_dsm.ReadAsArray().astype(float)

        feedback.setProgressText("Calculating wall height")

        if use_gpu:
            walls = wa_torch.findwalls_sp(dsm, walllimit, device, False)
        else:
            walls = wa.findwalls_sp(dsm, walllimit, False)

        wallssave = walls

        if use_gpu:
            wallssave = wallssave.cpu().detach().numpy()
        saverasternd(gdal_dsm, outputFileHeight, wallssave)

        if outputFileAspect:
            total = 100.0 / 180.0
            # outputFileAspect = self.parameterAsOutputLayer(parameters, self.OUTPUT_ASPECT, context)
            feedback.setProgressText("Calculating wall aspect")
            if use_gpu:
                dirwalls = wa_torch.filter1Goodwin_as_aspect_v3(
                    walls,
                    torch.tensor(1, device=device),
                    torch.tensor(dsm, device=device),
                    feedback,
                    torch.tensor(total, device=device),
                    device,
                )

                if use_gpu:
                    dirwalls = dirwalls.cpu().detach().numpy()
                saverasternd(gdal_dsm, outputFileAspect, dirwalls)
            else:

                dirwalls = wa.filter1Goodwin_as_aspect_v3(
                    walls,
                    1,
                    dsm,
                    feedback,
                    total,
                )
                saverasternd(gdal_dsm, outputFileAspect, dirwalls)
        else:
            feedback.setProgressText("Wall aspect not calculated")

        # Aggressive GPU memory cleanup
        if use_gpu and torch.cuda.is_available():
            feedback.setProgressText("Clearing GPU memory...")
            torch.cuda.synchronize()  # Ensure all GPU operations are complete
            torch.cuda.empty_cache()  # Clear unused GPU memory
            torch.cuda.reset_peak_memory_stats()  # Reset peak memory tracking
            torch.cuda.empty_cache()  # Clear again to be sure
            gc.collect()  # Force Python garbage collection
        elif use_gpu and torch.xpu.is_available():
            feedback.setProgressText("Clearing GPU memory...")
            torch.xpu.synchronize()  # Ensure all GPU operations are complete
            torch.xpu.empty_cache()  # Clear unused GPU memory
            torch.xpu.reset_peak_memory_stats()  # Reset peak memory tracking
            torch.xpu.empty_cache()  # Clear again to be sure
            gc.collect()  # Force Python garbage collection

        return {
            self.OUTPUT_HEIGHT: outputFileHeight,
            self.OUTPUT_ASPECT: outputFileAspect,
        }

    def name(self):
        return "Urban Geometry: Wall Height and Aspect"

    def displayName(self):
        return self.tr(self.name())

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return "Pre-Processor"

    def shortHelpString(self):
        return self.tr(
            "This algorithm identiies wall pixels and "
            "their height from ground and building digital surface models (DSM) by using a filter as "
            "presented by Lindberg et al. (2015a). Optionally, wall aspect can also be estimated using "
            "a specific linear filter as presented by Goodwin et al. (1999) and further developed by "
            "Lindberg et al. (2015b) to obtain the wall aspect. Wall aspect is given in degrees where "
            "a north facing wall pixel has a value of zero. The output of this plugin is used in other "
            "UMEP plugins such as SEBE (Solar Energy on Building Envelopes) and SOLWEIG (SOlar LongWave "
            "Environmental Irradiance Geometry model).\n"
            "------------------ \n"
            "Goodwin NR, Coops NC, Tooke TR, Christen A, Voogt JA (2009) Characterizing urban surface cover and structure with airborne lidar technology. Can J Remote Sens 35:297–309\n"
            "Lindberg F., Grimmond, C.S.B. and Martilli, A. (2015a) Sunlit fractions on urban facets - Impact of spatial resolution and approach Urban Climate DOI: 10.1016/j.uclim.2014.11.006\n"
            "Lindberg F., Jonsson, P. & Honjo, T. and Wästberg, D. (2015b) Solar energy on building envelopes - 3D modelling in a 2D environment Solar Energy 115 369–378"
            "-------------\n"
            "Full manual available via the <b>Help</b>-button."
        )

    def helpUrl(self):
        url = "https://umep-docs.readthedocs.io/en/latest/pre-processor/Urban%20Geometry%20Wall%20Height%20and%20Aspect.html"
        return url

    def tr(self, string):
        return QCoreApplication.translate("Processing", string)

    def icon(self):
        cmd_folder = Path(
            os.path.split(inspect.getfile(inspect.currentframe()))[0]
        ).parent
        icon = QIcon(str(cmd_folder) + "/icons/WallsIcon.png")
        return icon

    def createInstance(self):
        return ProcessingWallHeightAscpetAlgorithm()
