
[DEFAULT]

### INPUTS ###
# output path
output_dir=/home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup/solweig_out/
# working path
working_dir=/home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup/
# parameters json file
para_json_path=/home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup/save/solweig_out//solweig_parameters.json
# Input ground and building dsm
filepath_dsm=/vsizip//home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup.zip/DSM_GVC.tif
# Input vegetation dsm
filepath_cdsm=/vsizip//home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup.zip/CDSM_GVC.tif
# Input trunkzone vegetation dsm
filepath_tdsm=
# Input Digital Elevation Model
filepath_dem=
# Input Land cover dataset
filepath_lc=/vsizip//home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup.zip/LC_GVC.tif
# Input wall height raster
filepath_wh=/home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup/wallheight.tif
# Input wall aspect raster
filepath_wa=/home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup/wallaspect.tif
# Skyview factor files
input_svf=/home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup/skyview_out/svfs.zip
# Input file for anisotrophic sky
input_aniso=
# Point of Interest file for ground
poi_file=
poi_field=
# Input file for surface temperature data in v2026a (.txt file)
input_surf=
# Input file for wall temperture scheme (Wallenberg et al. 2025)
input_wall=
# Point of Interest file for walls
woi_file=
woi_field=
# input meteorolgical file (i.e. forcing file)
input_met=/home/lemap/Documents/suede/utils/tutorials/GVC_Validation_Setup/MetFile20100523_Prepared.txt

## input settings ##
# dates
# option to execute solweig outside of osgeo/qgis environment
standalone=0
# estimate diffuse and global shortwve radiation from global radiation (1)
onlyglobal=1
# use vegetation scheme (lindberg and grimmond, 2011, TAAC)
usevegdem=1
# consider leaf on trees full year (1)
conifer_bool=0
# consider person as a cylinder (1) or a box (0)
cyl=1
# Location of model domain
lat=57.68699204806551
lon=11.962800222474023
#utc time given in meteorological forcing file
utc=0
# scale between horisontal and vertical resolution (1 = 1 meter pixel reolution, 0.5 = 2)
scale=0.5
# Set to 1 if an EPW file is used as meteorological forcing data
useepwfile=0
# land cover scheme activated (1) (Lindberg et al. 2016 UC)
landcover=1
# use dem and dsm to identify building pixels (0) else, land cover will be used (0)
demforbuild=0
# use anisotrphic sky (Wallenberg et al. XXXX and Wallenberg et al. XXXX)
aniso=0
# use the surface temperature parameterization v2026a
groundmodel=1
# use the outgoing longwave radiation computation scheme v2026a
outgoinglongwave=1
# use wall surface temperature scheme (Wallenberg et al. 2025, GMD)
wallscheme=0
# If building materials is not included in lc, then this is used for all buildings (Wood, Brick or Concrete)
walltype=100
# output settings
outputtmrt=1
outputkup=1
outputkdown=1
outputlup=1
outputldown=1
outputsh=1
savebuild=1
outputkdiff=0
outputtreeplanter=0
wallnetcdf=0
# calculation mode (cpu or gpu)
calculation_mode=cpu
#-------------------------------------------------------
# dates - used if an EPW-file is used
#-------------------------------------------------------
# year,month,day,hour	## the start date/time for period of interest
date1=2018,5,1,0
# year,month,day,hour	# end date/time
date2=2018,8,1,18

